######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 28 01:51:25 2009
######################################################################

TEMPLATE = subdirs
SUBDIRS = mac \ 
	ippacket \
	ipaddress \
        frame
#	cable
# Input
