#ifndef BASICNETLIB_GLOBAL_H
#define BASICNETLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASICNETLIB_LIBRARY)
#  define BASICNETLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BASICNETLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BASICNETLIB_GLOBAL_H
